### ISSUE TITLE
Add text to Share link

### ISSUE THREAD

**Issue by kinow** [avowkind/groat#1]
Right now when a user clicks on Share, then selects Twitter, the pop-up contains the link, but no text.

Probably around [here](https://github.com/avowkind/groat/blob/5a098242efd85866035c442802f9850767722262/themes/landscape/source/js/script.js#L58), add the data-text (here's [what I did for my blog](https://github.com/kinow/kinoshita.eti.br/blob/8bf7e14de9b8c384c4eacd3dd9684bbe7b562ccc/templates/macros_tweet.html#L7)).

**Comment by avowkind** [comment]
I see what you mean - it will be in the bootstrap-blog theme as that's what I'm using. the link for 'what I did for my blog' in your comment points to the same location as 'here'.

**Comment by kinow** [comment]
Oh, lack of coffee, sorry. Updated the link. If you go to any post on my blog and click on the Twitter icon, you can test it and see the text + URL + the opensource hashtag
